//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AZ_Quiz.Properties {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AZ_Quiz.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný AIDS
        ///Atmosféra
        ///avokádo
        ///Anakonda
        ///Aligátor
        ///bakterie
        ///buňka
        ///Bonsaj
        ///blána
        ///Běžníkovití
        ///Bělásek zelný
        ///Botanika
        ///Bakteriofág
        ///Biosféra
        ///Bezocasí
        ///Borelióza
        ///Cévní
        ///Cysta
        ///Cejn velký
        ///Celulóza
        ///Candát
        ///Čmelák
        ///Červotoč
        ///Lupenotvarné
        ///Čolek
        ///Dělnice
        ///Dýchání
        ///Dřevokazné
        ///Dřevomorka
        ///Dýchací
        ///Dezinfekce
        ///Encefalitida
        ///elektrický
        ///Ekologie
        ///Flemming
        ///Flóra
        ///Goliáš
        ///Gorila
        ///Gazela
        ///Hmyz
        ///Hlístoun stříbřitý
        ///Hlavonožce
        ///Hlavohruď
        ///Hermafroditi
        ///Hlavonožci
        ///Hroznýš
        ///Chloroplast
        ///Chlorofyl
        ///Chitin
        ///Chrupavčitou        /// [zbytek řetězce byl zkrácen];.
        /// </summary>
        internal static string Answers {
            get {
                return ResourceManager.GetString("Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AZkvíz_logo {
            get {
                object obj = ResourceManager.GetObject("AZkvíz logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlueTabel {
            get {
                object obj = ResourceManager.GetObject("BlueTabel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OrangeTabel {
            get {
                object obj = ResourceManager.GetObject("OrangeTabel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pozadí_AZ_Quiz {
            get {
                object obj = ResourceManager.GetObject("pozadí_AZ_Quiz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Jak se nazývá nemoc způsobená viry, která se přenáší pohlavním stykem?
        ///Jak se nazývá plynný obal Země?
        ///Ovocem s největší kalorickou hodnotu je _________.
        ///Největší had na světě (škrtič), žijící v Amazonce _________.
        ///Jak se nazývá největší krokodýl?
        ///Co jsou stafylokoky a streptokoky? (Jsou tyčinkovité, kulovité, hroznovité, atd.)
        ///Jak se nazývá základní stavební a funkční jednotka organismu?
        ///Strom nebo rostlina pěstovaná v ploché nádobě se nazývá _________.
        ///Jak se nazývá hmota, která je např. u žab mez [zbytek řetězce byl zkrácen];.
        /// </summary>
        internal static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
    }
}
