//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AZ_Quiz.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AZ_Quiz.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIDS
        ///Atmosféra
        ///avokádo
        ///Anakonda
        ///Aligátor
        ///bakterie
        ///buňka
        ///Bonsaj
        ///blána
        ///Běžníkovití
        ///Bělásek zelný
        ///Botanika
        ///Bakteriofág
        ///Biosféra
        ///Bezocasí
        ///Borelióza
        ///Cévní
        ///Cysta
        ///Cejn velký
        ///Celulóza
        ///Candát
        ///Čmelák
        ///Červotoč
        ///Lupenotvarné
        ///Čolek
        ///Dělnice
        ///Dýchání
        ///Dřevokazné
        ///Dřevomorka
        ///Dýchací
        ///Dezinfekce
        ///Encefalitida
        ///elektrický
        ///Ekologie
        ///Flemming
        ///Flóra
        ///Goliáš
        ///Gorila
        ///Gazela
        ///Hmyz
        ///Hlístoun stříbřitý
        ///Hlavonožce
        ///Hlavohruď
        ///Hermafroditi
        ///Hlavonožci
        ///Hroznýš
        ///Chloroplast
        ///Chlorofyl
        ///Chitin
        ///Chrupavčitou        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Answers {
            get {
                return ResourceManager.GetString("Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AZkvíz_logo {
            get {
                object obj = ResourceManager.GetObject("AZkvíz logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlueTabel {
            get {
                object obj = ResourceManager.GetObject("BlueTabel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OrangeTabel {
            get {
                object obj = ResourceManager.GetObject("OrangeTabel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jak se nazývá nemoc způsobená viry, která se přenáší pohlavním stykem?
        ///Jak se nazývá plynný obal Země?
        ///Ovocem s největší kalorickou hodnotu je _________.
        ///Největší had na světě (škrtič), žijící v Amazonce _________.
        ///Jak se nazývá největší krokodýl?
        ///Co jsou stafylokoky a streptokoky? (Jsou tyčinkovité, kulovité, hroznovité, atd.)
        ///Jak se nazývá základní stavební a funkční jednotka organismu?
        ///Strom nebo rostlina pěstovaná v ploché nádobě se nazývá _________.
        ///Jak se nazývá hmota, která je např. u žab mez [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
    }
}
